import type { AgentRegistryEntry, WorkflowState } from "../types/agent";

export const mockAgents: AgentRegistryEntry[] = [
  {
    id: "claude-code",
    displayName: "Claude Code",
    provider: "Anthropic",
    managedSdkDependencyId: "claude-sdk",
    launch: { kind: "cli", command: "claude", executableName: "claude" },
    supportedInteractionModes: ["cli", "native-desktop"],
    availabilityState: "unknown",
    capabilityTags: ["coding", "cli", "agent"],
    agentOrigin: "builtin",
  },
  {
    id: "opencode",
    displayName: "OpenCode",
    provider: "OpenCode",
    launch: { kind: "cli", command: "opencode", executableName: "opencode" },
    supportedInteractionModes: ["cli"],
    availabilityState: "unknown",
    capabilityTags: ["coding", "cli", "open-source"],
    agentOrigin: "builtin",
  },
  {
    id: "codex-cli",
    displayName: "Codex CLI",
    provider: "OpenAI",
    managedSdkDependencyId: "codex-sdk",
    launch: { kind: "cli", command: "codex", executableName: "codex" },
    supportedInteractionModes: ["cli", "native-desktop"],
    availabilityState: "unknown",
    capabilityTags: ["coding", "cli", "agent"],
    agentOrigin: "builtin",
  },
  {
    id: "gemini-cli",
    displayName: "Gemini CLI",
    provider: "Google",
    launch: { kind: "cli", command: "gemini", executableName: "gemini" },
    supportedInteractionModes: ["cli", "browser"],
    availabilityState: "unknown",
    capabilityTags: ["coding", "cli", "browser"],
    agentOrigin: "builtin",
  },
  {
    id: "antigravity-cli",
    displayName: "Antigravity CLI",
    provider: "Google",
    launch: { kind: "cli", command: "agy", executableName: "agy" },
    supportedInteractionModes: ["cli"],
    availabilityState: "unknown",
    capabilityTags: ["coding", "cli", "agent"],
    agentOrigin: "builtin",
  },
  // The seven expanded CLIs. `acp` and `legacy` are the same capability tags the native
  // registry seeds, so the create-session dialog reads one vocabulary in both runtimes.
  ...([
    ["qwen-code", "Qwen Code", "Alibaba", "qwen", "acp"],
    ["kimi-cli", "Kimi Code CLI", "Moonshot AI", "kimi", "acp"],
    ["qoder-cli", "Qoder CLI", "Qoder", "qoder", "acp"],
    ["codebuddy-code", "CodeBuddy Code", "Tencent", "codebuddy", "acp"],
    ["copilot-cli", "GitHub Copilot CLI", "GitHub", "copilot", "acp"],
    ["cursor-agent-cli", "Cursor Agent CLI", "Cursor", "agent", "acp"],
    ["iflow-cli", "iFlow CLI", "iFlow", "iflow", "legacy"],
  ] as const).map(([id, displayName, provider, command, transport]): AgentRegistryEntry => ({
    id,
    displayName,
    provider,
    launch: { kind: "cli", command, executableName: command },
    supportedInteractionModes: ["cli"],
    availabilityState: "unknown",
    capabilityTags: transport === "acp" ? ["coding", "cli", "agent", "acp"] : ["coding", "cli", "legacy", "terminal-only"],
    agentOrigin: "builtin",
  })),
  {
    id: "onepiece",
    displayName: "OnePiece",
    provider: "VaneHub",
    launch: { kind: "api" },
    supportedInteractionModes: ["api"],
    availabilityState: "unavailable",
    unavailableReason: "OnePiece requires provider configuration.",
    capabilityTags: ["coding", "api", "agent", "native"],
    agentOrigin: "builtin",
  },
];

export const mockWorkflowState: WorkflowState = {
  activeAgentId: null,
  activeInteractionMode: null,
  lifecycleState: "idle",
  intent: "Current development workflow",
};
