[CmdletBinding()]
param(
    [string]$ArchiveRoot
)

if ([string]::IsNullOrWhiteSpace($ArchiveRoot)) {
    $repositoryRoot = Split-Path -Parent $PSScriptRoot
    $ArchiveRoot = Join-Path $repositoryRoot "openspec\changes\archive"
}

$resolvedArchiveRoot = Resolve-Path -LiteralPath $ArchiveRoot -ErrorAction Stop
$archiveDirectories = @(
    Get-ChildItem -LiteralPath $resolvedArchiveRoot.Path -Directory |
        Where-Object { $_.Name -match '^\d{4}-\d{2}-\d{2}-.+$' } |
        Sort-Object Name
)
$catalogEntries = @()

$lines = @(
    '# OpenSpec Archive Index'
    ''
    '> Generated by `scripts/Update-OpenSpecArchiveIndex.ps1`. Do not edit manually.'
    ''
    'Online archive location: `openspec/changes/archive/`'
    ''
    '## Archived Changes'
    ''
)

if ($archiveDirectories.Count -eq 0) {
    $lines += 'No online archives recorded.'
} else {
    $lines += '| Archived on | Change | Capabilities | Path |'
    $lines += '| --- | --- | --- | --- |'

    foreach ($archiveDirectory in $archiveDirectories) {
        $date = $archiveDirectory.Name.Substring(0, 10)
        $changeName = $archiveDirectory.Name.Substring(11)
        $relativePath = "openspec/changes/archive/$($archiveDirectory.Name)/"
        $artifacts = @('proposal', 'design', 'tasks', 'verification') | Where-Object {
            Test-Path -LiteralPath (Join-Path $archiveDirectory.FullName "$_.md")
        }
        $specsPath = Join-Path $archiveDirectory.FullName 'specs'
        $capabilities = @()
        if (Test-Path -LiteralPath $specsPath -PathType Container) {
            $capabilities = @(
                Get-ChildItem -LiteralPath $specsPath -Directory |
                    Where-Object { Test-Path -LiteralPath (Join-Path $_.FullName 'spec.md') -PathType Leaf } |
                    Sort-Object Name |
                    Select-Object -ExpandProperty Name
            )
        }
        $capabilitySummary = if ($capabilities.Count -eq 0) { '-' } else { $capabilities -join ', ' }
        $lines += "| $date | $changeName | $capabilitySummary | ``$relativePath`` |"
        $catalogEntries += [ordered]@{
            archivedOn = $date
            changeName = $changeName
            path = $relativePath
            artifacts = @($artifacts)
            capabilities = @($capabilities)
        }
    }
}

$lines += ''
$lines += 'Cold-archive destinations are recorded in `openspec/archive-cold-migrations.md`.'

$indexPath = Join-Path $resolvedArchiveRoot.Path 'README.md'
[System.IO.File]::WriteAllText(
    $indexPath,
    (($lines -join [Environment]::NewLine) + [Environment]::NewLine),
    [System.Text.UTF8Encoding]::new($false)
)

$catalogPath = Join-Path $resolvedArchiveRoot.Path 'archive-index.json'
$catalog = [ordered]@{
    schemaVersion = 1
    archives = @($catalogEntries)
}
[System.IO.File]::WriteAllText(
    $catalogPath,
    (($catalog | ConvertTo-Json -Depth 4) + [Environment]::NewLine),
    [System.Text.UTF8Encoding]::new($false)
)

Write-Output "Updated $indexPath and $catalogPath with $($archiveDirectories.Count) archive entries."
