import type { RemoteTerminalStatus } from "../types/remote-terminal";

export function RemoteTerminalStatusPanel({ status }: { status: RemoteTerminalStatus }) { return <div className="rounded border border-border px-2 py-1 text-xs" role="status">{status.state}{status.endpoint ? ` · ${status.endpoint.user}@${status.endpoint.host}:${status.endpoint.port}` : ""}</div>; }
export function RemoteTerminalTrustPanel({ required, onConfirm }: { required: boolean; onConfirm?: () => void }) { if (!required) return null; return <div className="rounded border border-amber-500/40 bg-amber-500/10 p-2 text-xs">Host key confirmation required<button className="ml-2 underline" onClick={onConfirm} type="button">Confirm</button></div>; }
export function RemoteTerminalCapturePanel({ enabled, onToggle }: { enabled: boolean; onToggle: () => void }) { return <button className="h-7 rounded border border-border px-2 text-xs hover:bg-muted" onClick={onToggle} type="button">Capture: {enabled ? "on" : "off"}</button>; }
export function RemoteTerminalTemplatePanel({ names, onInsert, onRun }: { names: string[]; onInsert?: (name: string) => void; onRun?: (name: string) => void }) { return <div className="flex gap-1 text-xs">{names.length ? names.map((name) => <span className="rounded border border-border px-1" key={name}>{name}<button className="ml-1 underline" onClick={() => onInsert?.(name)} type="button">Insert</button><button className="ml-1 underline" onClick={() => onRun?.(name)} type="button">Run</button></span>) : "No command templates"}</div>; }
export function RemoteTerminalHistoryPanel({ count, page, onPrevious, onNext }: { count: number; page: number; onPrevious?: () => void; onNext?: () => void }) { return <div className="flex items-center gap-2 text-xs">Run history: {count}<button className="underline" disabled={page === 0} onClick={onPrevious} type="button">Previous</button><button className="underline" onClick={onNext} type="button">Next</button></div>; }
export function RemoteTerminalSearchPanel({ query, onChange }: { query: string; onChange: (value: string) => void }) { return <input aria-label="Search terminal output" className="h-7 rounded border border-border px-2 text-xs" value={query} onChange={(event) => onChange(event.target.value)} placeholder="Search output" />; }
export function RemoteTerminalPurgeButton({ onPurge }: { onPurge: () => void }) { return <button className="h-7 rounded border border-destructive px-2 text-xs text-destructive" onClick={() => { if (window.confirm("Purge captured terminal output?")) onPurge(); }} type="button">Purge capture</button>; }
